### ISSUE TITLE
init project error in windows

### ISSUE THREAD

**Issue by CurryHan** [jaywcjlove/rdoc#3]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\rdoc\node_modules\create
-spare-webpack-plugin\index.js:26
      const { dir, ...otherOtions } = directoryTrees;
                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\rdoc\src\conf\webpack.config.dev.js:7:34)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

**Comment by CurryHan** [comment]
node version v8.1.1

**Comment by jaywcjlove** [comment]
const 不支持？不是 4.0 就支持了const了？你看官方 v8.9.3 可以用不，回头我测试一下。

**Comment by CurryHan** [comment]
@jaywcjlove 8.9.4可以用,8.1.1会报错

**Comment by jaywcjlove** [comment]
@CurryHan 👌
