### ISSUE TITLE
发布到github

### ISSUE THREAD

**Issue by CurryHan** [jaywcjlove/rdoc#7]
![image](https://user-images.githubusercontent.com/14214176/37392180-651fe98c-27a8-11e8-95d1-6c45dfcd06df.png)

貌似是卡在这里了,一直在等待.
不一定是rdoc的问题,有什么建议吗@jaywcjlove

**Comment by jaywcjlove** [comment]
```bash
rdoc --publish https://github.com/react-doc/react-doc.github.io.git --branch master
```

@CurryHan  你的配置是这样子的吗？

**Comment by jaywcjlove** [comment]
@CurryHan 还有一个点，可能你需要翻墙

你GitHub可以打开，应该不需要翻墙的样子。

**Comment by CurryHan** [comment]
```shell
"deploy":"rdoc --publish https://github.com/CurryHan/CurryHan.github.io.git"
```
repository建了个gh-pages分支,
github应该没有被墙掉,可以push的

**Comment by jaywcjlove** [comment]
@CurryHan 我发现，我在公司GitHub仓库都克隆不下来。 回家好了，不知道什么情况 你拿国产 gitee.com 测试看看

**Comment by jaywcjlove** [comment]
@CurryHan 我在公司使用美国 vpn 主机，代码push 上来了

> 更新了个新版本，增加了 deploy 部署代码提示。

**Comment by CurryHan** [comment]
@jaywcjlove  push出错,应该无法验证我的身份,怎么去验证身份
```shell
F:\rdoc\NDoc>npm run deploy

> NDoc@1.0.0 deploy F:\rdoc\NDoc
> rdoc --publish https://github.com/CurryHan/CurryHan.github.io.git

You need to run the "npm run build" command.
The F:\rdoc\NDoc\.rdoc-dist folder does net exist!


F:\rdoc\NDoc>npm run build

> NDoc@1.0.0 build F:\rdoc\NDoc
> rdoc -d home,develop --build


Compiled successfully.


F:\rdoc\NDoc>npm run deploy

> NDoc@1.0.0 deploy F:\rdoc\NDoc
> rdoc --publish https://github.com/CurryHan/CurryHan.github.io.git

  Start public to your git repo
  https://github.com/CurryHan/CurryHan.github.io.git

{ ProcessError:
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Administrator@WIN-GU1VOC7DGJ6.(
none)')

    at ChildProcess.<anonymous> (F:\rdoc\rooc3.15\rdoc\node_modules\gh-pages\lib
\git.js:42:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  code: 128,
  message: '\n*** Please tell me who you are.\n\nRun\n\n  git config --global us
er.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto se
t your account\'s default identity.\nOmit --global to set the identity only in t
his repository.\n\nfatal: unable to auto-detect email address (got \'Administrat
or@WIN-GU1VOC7DGJ6.(none)\')\n',
  name: 'ProcessError' }
```

**Comment by CurryHan** [comment]
@jaywcjlove  可以 没问题 push成功.
